### ISSUE TITLE
the LocalDLMEmulator in shaded/bkshade jar can't start bk

### ISSUE THREAD

**Issue by ArvinDevel** [ArvinDevel/shennong#1]
After Dlog bump bk version to 4.6, the LocalDLMEmulator in shaded/bkshade jar can't start bk. The problem is from  [bump-bk](https://github.com/apache/distributedlog/issues/197). But the effected is only restricted in shaded & bkshade jar. In that pr, The main change is from zkVersion to LongVersion, is that has an potential effect?

A piece of error:
java.lang.NullPointerException
	at dlshade.org.apache.bookkeeper.util.LocalBookKeeper.cleanupDirectories(LocalBookKeeper.java:128)
	at dlshade.org.apache.bookkeeper.util.LocalBookKeeper.startLocalBookiesInternal(LocalBookKeeper.java:309)
	at dlshade.org.apache.bookkeeper.util.LocalBookKeeper.startLocalBookies(LocalBookKeeper.java:251)
	at org.apache.distributedlog.LocalDLMEmulator$1.run(LocalDLMEmulator.java:146)

**Comment by ArvinDevel** [comment]
The test is in dlog-bk-common-test module.

**Comment by ArvinDevel** [comment]
`bkshade-tests` is generated by shade plugin's `<shadeTestJar>true</shadeTestJar>` option, we should copy that jar to local repository manually.

**Comment by ArvinDevel** [comment]
Another thing, because bk 4.6 has refactored. We should include bk-common in bkshade.
add`<include>org.apache.bookkeeper:bookkeeper-common</include>` in bkshade's               `<artifactSet>`

**Comment by ArvinDevel** [comment]
close the issue since it was solved
